### PR TITLE
Fix deadlock

### PR DESCRIPTION
**Pull request by benpye**
This fixes the deadlock issue described in #8 .

### CODE REVIEW

**Comment by ViRb3** [comment]
Works! Though a note from official docs:

The Map type is specialized. Most code should use a plain Go map instead, with separate locking or coordination, for better type safety and to make it easier to maintain other invariants along with the map content.

The Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex.

**Comment by benpye** [comment]
Fair enough @ViRb3 - I did miss that note.

**Comment by benpye** [comment]
I missed the call to `delete`, just added that back!

**Comment by nzoschke** [comment]
Big +1 on this. On master the example doesn’t play anything and hangs. This PR fixes it.

**Comment by benpye** [comment]
@xplodwild Hey, is there any chance of this getting merged in the near future? Otherwise I might take a fork and push my changes there. It seems like this is useful to other people as well.

**Comment by xplodwild** [comment]
I just realized I had no notifications turned on for the repository so I had missed the current PRs. I'll be reviewing them throughout the day.

**Comment by benpye** [comment]
No worries @xplodwild , just glad you saw this now. I didn't want to have to fork the project so I'm glad you're still keeping it up to date!

**Pull request merged**
